/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChecklistsRouteImport } from './routes/checklists'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as OperatorsIdRouteImport } from './routes/operators.$id'
import { Route as SitesIdRouteImport } from './routes/sites.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistsRoute = ChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsIdRoute = OperatorsIdRouteImport.update({
  id: '/operators/$id',
  path: '/operators/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesIdRoute = SitesIdRouteImport.update({
  id: '/sites/$id',
  path: '/sites/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/directory': typeof DirectoryRoute
  '/saved': typeof SavedRoute
  '/operators/$id': typeof OperatorsIdRoute
  '/sites/$id': typeof SitesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/directory': typeof DirectoryRoute
  '/saved': typeof SavedRoute
  '/operators/$id': typeof OperatorsIdRoute
  '/sites/$id': typeof SitesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checklists': typeof ChecklistsRoute
  '/directory': typeof DirectoryRoute
  '/saved': typeof SavedRoute
  '/operators/$id': typeof OperatorsIdRoute
  '/sites/$id': typeof SitesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checklists'
    | '/directory'
    | '/saved'
    | '/operators/$id'
    | '/sites/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checklists'
    | '/directory'
    | '/saved'
    | '/operators/$id'
    | '/sites/$id'
  id:
    | '__root__'
    | '/'
    | '/checklists'
    | '/directory'
    | '/saved'
    | '/operators/$id'
    | '/sites/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChecklistsRoute: typeof ChecklistsRoute
  DirectoryRoute: typeof DirectoryRoute
  SavedRoute: typeof SavedRoute
  OperatorsIdRoute: typeof OperatorsIdRoute
  SitesIdRoute: typeof SitesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklists': {
      id: '/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof ChecklistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators/$id': {
      id: '/operators/$id'
      path: '/operators/$id'
      fullPath: '/operators/$id'
      preLoaderRoute: typeof OperatorsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/$id': {
      id: '/sites/$id'
      path: '/sites/$id'
      fullPath: '/sites/$id'
      preLoaderRoute: typeof SitesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChecklistsRoute: ChecklistsRoute,
  DirectoryRoute: DirectoryRoute,
  SavedRoute: SavedRoute,
  OperatorsIdRoute: OperatorsIdRoute,
  SitesIdRoute: SitesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
